### ISSUE TITLE
arc can't open side bar

### ISSUE THREAD

**Issue by cryzlasm** [MichaelYuhe/Artifacts-for-ChatGPT#2]
![image](https://github.com/MichaelYuhe/Artifacts-for-ChatGPT/assets/20424580/a83baa55-d5cf-44bd-ae85-d35a11071b9c)

arc can't open side bar

google chrome can open

**Comment by cryzlasm** [comment]
![image](https://github.com/MichaelYuhe/Artifacts-for-ChatGPT/assets/20424580/48e8e1ec-c30b-41fc-97b2-77c0338361e8)

**Comment by MichaelYuhe** [comment]
Arc doesn't support sidepanel api yet.
